### ISSUE TITLE
Set up 2nd Demo Service 

### ISSUE THREAD

**Issue by jcvillalta03** [NVISIA/chicago-microservices-meetup#7]
(and develop idea for what demo services are supposed to represent)

**Comment by justinjohn83** [comment]
Allow starting up multiple instances of the demo service that can call other demo services and introduce options to cause failures and latencies so that we can demonstrate the capabilities of spring boot admin, spring cloud sleuth, and zipkin.

**Comment by jcvillalta03** [comment]
Closed with #12
